### ISSUE TITLE
Native store parse error

### ISSUE THREAD

**Issue by danielkcz** [jutaz/flatty#2]
You have asked for it ;)

https://dl.dropboxusercontent.com/u/1791518/test/models.db

```
SyntaxError: Unexpected token l
  at Object.parse (native)
  at nativeStore.parse (C:\workspace\alpha\node_modules\flatty\stores\native.js:
38:23)
  at new engine (C:\workspace\alpha\node_modules\flatty\main.js:17:26)
```

**Comment by danielkcz** [comment]
That was fast, it works. Thanks !

**Comment by jutaz** [comment]
Let me know, if any help is needed ;)
As I see, you are making a game, so, if it runs on node, you may be interested in ’native-engine’ branch - it`s on it`s way to be written in c++

**Comment by danielkcz** [comment]
Thanks, but I am going to use flatty just for development purposes. Production data will be in Redis.

**Comment by jutaz** [comment]
Cool, this is what it is intended to be used for ;)
