### ISSUE TITLE
Another parse error for native store

### ISSUE THREAD

**Issue by danielkcz** [jutaz/flatty#4]
Too bad it doesn't stay more information on that parse error. Hopefully you will be able to pinpoint issue.

```
SyntaxError: Unexpected token n
  at Object.parse (native)
  at nativeStore.parse (c:\workspace\alpha\node_modules\flatty\stores\native.js:45:23)
```

https://dl.dropboxusercontent.com/u/1791518/test/components.db

**Comment by jutaz** [comment]
Yes, easy one, will fix in 30 min :)

**Comment by jutaz** [comment]
Fixed ;)
