### ISSUE TITLE
Allow id in set method to be undefined

### ISSUE THREAD

**Issue by danielkcz** [jutaz/flatty#5]
This is merely a suggestion. Could you maybe handle if there is falsy value in first argument and generate key instead of using it as valid id ?

```
flatty.set(undefined, data, function(key) {
    // key should be generated, currently returns undefined
});
```

Edit: To clarify this issue, I want to avoid having `if...else` depending on if I know the ID or not.

**Comment by danielkcz** [comment]
That was easy I see, thanks ! :)

**Comment by jutaz** [comment]
Np, give me more stuff to fix ;)

**Comment by danielkcz** [comment]
Well, you could fix my game :D Don't worry, I am sure there will be more things incoming.

**Comment by jutaz** [comment]
If it is OSS and there is some server-side stuff - I could help ;)

**Comment by danielkcz** [comment]
No it's not open source, but it has server side as it is mmorpg :P I am not doing it alone actually, more people involved, but I am lead developer.

**Comment by jutaz** [comment]
Hm, that looks interesting. Can we hop on private chat, maybe? ;)

**Comment by danielkcz** [comment]
https://gitter.im/BlackDice

**Comment by danielkcz** [comment]
Not exactly private, but if you got something better, tell me.

**Comment by jutaz** [comment]
Fits good enough ;)
Can you add me to some chat? 404
