### ISSUE TITLE
Leaking global variable

### ISSUE THREAD

**Issue by danielkcz** [jutaz/flatty#6]
Not cool, bro :) It popped at me during Mocha tests where this check is enabled by default.

```
Error: global leaks detected: parsed, newlinePos, meta, splitted, id, arr
```

https://github.com/jutaz/flatty/blob/master/stores/native.js#L29
https://github.com/jutaz/flatty/blob/master/stores/native.js#L32
https://github.com/jutaz/flatty/blob/master/stores/native.js#L33
https://github.com/jutaz/flatty/blob/master/stores/native.js#L39
https://github.com/jutaz/flatty/blob/master/stores/native.js#L44
https://github.com/jutaz/flatty/blob/master/main.js#L80

**Comment by danielkcz** [comment]
Oh man, do you really have to ignore me like this? Did I said something wrong? I see your activity in other repositories. Why would you act like this ? We talked about honesty, do you remember ?

**Comment by jutaz** [comment]
No, sorry, I'm not ignoring, just have shit ton of work. Yes, will fix this later today

**Comment by danielkcz** [comment]
Well I mean ignoring on email too ;) You just vanished without a word... This is not really important.
